### ISSUE TITLE
Keep forces that are too specific in a separate module?

### ISSUE THREAD

**Issue by golobor** [mirnylab/polychrom#13]
We had this issue before with opemmlib that the space of standard forces was too loaded with project-specific forces.
I'd suggest to either create a separate module for "special" forces or even keeping them in a separate repo. The only question is which forces are "special" and which are general. My suggestion would be to (a) check if there will be more than two-three consumers for the force and (b) see if a force can be defined outside of a specific biological context in general geometric terms
https://github.com/mirnylab/polychrom/blob/5cfc312252a7158a4c88eaeef92b1fc4116e6ab4/polychrom/forces.py#L413

**Comment by mimakaev** [comment]
Agreed on this issue. 

This force was already used by at least 2 people, and it looks like a valuable force to have. I was thinking it may be nice to have a multi-compartment force in the library, so decided to go with this one.

**Comment by golobor** [comment]
Ah, I/c. How about then generalizing it to N interactions (the energy expression can be populated automatically) and calling it something like heteropolymer?

**Comment by mimakaev** [comment]
I'll offer it to Simon!

**Comment by SGrosse-Holz** [comment]
Thanks for the suggestion Anfon!

**Comment by golobor** [comment]
!!awesome!!
(1) Should we test if the energy term is non-zero before adding it? The downside is that we won't be able to change it dynamically. :(
(2) should we rename it to something in the language of polymer physics, i.e. heteropolymer_ssw? Compartments is just one of the infinite applications of this force and we don't have to necessarily lock ourselves into the biological domain. Besides, we're dealing with abstractions, so I find that it's nice to separate what we're doing from what we're trying to model. I.e. what if it turns out that compartments are produced by some other physical mechanism? Of course, it's unlikely, but that's the idea. Besides, other forces so far are named via the abstraction they are implementing and not what they are trying to achive (i.e. spherical_confinement and not lamina confinement). Same argument applies to the other force (laminaAttraction)

**Comment by mimakaev** [comment]
There could be a flag keep_0_terms that should be false by default.

**Comment by SGrosse-Holz** [comment]
Added the suggestions to the compartment-force branch (which is now a misnomer I guess:D)

**Comment by golobor** [comment]
looks really good, thank you!
one minor suggestion - should it be spherical_shell_well? :)
