### ISSUE TITLE
Forcekits: too difficult for new users, or useful

### ISSUE THREAD

**Issue by mimakaev** [mirnylab/polychrom#5]
After receiving feedback from a new user, Jeremy, on forcekits, I think we should discuss again how useful they are. 

-- Passing functions to other functions is somewhat unfamiliar for beginners 
-- It is unclear what does a forcekit actually do - maybe better documentation/examples will solve this?

What do others think about forcekits? 

Max

**Comment by jaowen** [comment]
To clarify, I was mostly saying they seemed a little inelegant to have, given that there is only one ("polymerChains"). I also think example.py might benefit from having the code currently in forcekits.py explicitly included and commented upon.
