### ISSUE TITLE
hdf5 file close function

### ISSUE THREAD

**Issue by hbbrandao** [mirnylab/polychrom#8]
I think we should add hdf5 file closing function. Jupyter notebooks are complaining about too many files opened for generating contact maps.

**Comment by hbbrandao** [comment]
To clarify, these are files opened using polychrom.hdf5_format.load_block()

**Comment by nvictus** [comment]
It uses a `with` block (context manager), so the files should be closed once the data is read.

https://github.com/mirnylab/polychrom/blob/master/polychrom/hdf5_format.py#L84-L85

**Comment by hbbrandao** [comment]
Thanks, Nezar. The issue seemed to be with the limit on open files set by the operating system - I was opening a number of files below (but close) to the limit - resulting in the error. Marking this issue as closed.
